export type DrawDuelWordEntry = {
  word: string;
  aliases: string[];
};

export type DrawDuelWordCategory =
  | "animal"
  | "body-symbol"
  | "food"
  | "hobby"
  | "household"
  | "nature"
  | "place"
  | "vehicle";

const wordCategoryRanges = [
  { category: "animal", end: 30 },
  { category: "food", end: 65 },
  { category: "vehicle", end: 85 },
  { category: "household", end: 130 },
  { category: "nature", end: 155 },
  { category: "place", end: 175 },
  { category: "hobby", end: 190 },
  { category: "body-symbol", end: 200 },
] satisfies { category: DrawDuelWordCategory; end: number }[];

export const drawDuelWordBank = [
  { word: "고양이", aliases: ["냥이", "cat"] },
  { word: "강아지", aliases: ["개", "puppy", "dog"] },
  { word: "토끼", aliases: ["rabbit", "bunny"] },
  { word: "코끼리", aliases: ["elephant"] },
  { word: "기린", aliases: ["giraffe"] },
  { word: "사자", aliases: ["lion"] },
  { word: "호랑이", aliases: ["tiger"] },
  { word: "곰", aliases: ["bear"] },
  { word: "판다", aliases: ["panda"] },
  { word: "원숭이", aliases: ["monkey"] },
  { word: "돼지", aliases: ["pig"] },
  { word: "소", aliases: ["cow"] },
  { word: "말", aliases: ["horse"] },
  { word: "양", aliases: ["sheep"] },
  { word: "닭", aliases: ["chicken"] },
  { word: "오리", aliases: ["duck"] },
  { word: "펭귄", aliases: ["penguin"] },
  { word: "독수리", aliases: ["eagle"] },
  { word: "올빼미", aliases: ["owl"] },
  { word: "물고기", aliases: ["fish"] },
  { word: "상어", aliases: ["shark"] },
  { word: "고래", aliases: ["whale"] },
  { word: "돌고래", aliases: ["dolphin"] },
  { word: "거북이", aliases: ["turtle"] },
  { word: "뱀", aliases: ["snake"] },
  { word: "개구리", aliases: ["frog"] },
  { word: "악어", aliases: ["crocodile", "alligator"] },
  { word: "나비", aliases: ["butterfly"] },
  { word: "벌", aliases: ["bee"] },
  { word: "달팽이", aliases: ["snail"] },
  { word: "사과", aliases: ["애플", "apple"] },
  { word: "바나나", aliases: ["banana"] },
  { word: "딸기", aliases: ["strawberry"] },
  { word: "포도", aliases: ["grape"] },
  { word: "수박", aliases: ["watermelon"] },
  { word: "파인애플", aliases: ["pineapple"] },
  { word: "당근", aliases: ["carrot"] },
  { word: "옥수수", aliases: ["corn"] },
  { word: "버섯", aliases: ["mushroom"] },
  { word: "피자", aliases: ["pizza"] },
  { word: "햄버거", aliases: ["버거", "hamburger", "burger"] },
  { word: "핫도그", aliases: ["hotdog"] },
  { word: "샌드위치", aliases: ["sandwich"] },
  { word: "김밥", aliases: ["gimbap"] },
  { word: "초밥", aliases: ["스시", "sushi"] },
  { word: "라면", aliases: ["ramen"] },
  { word: "떡볶이", aliases: ["tteokbokki"] },
  { word: "만두", aliases: ["dumpling"] },
  { word: "아이스크림", aliases: ["ice cream"] },
  { word: "케이크", aliases: ["cake"] },
  { word: "도넛", aliases: ["donut", "doughnut"] },
  { word: "쿠키", aliases: ["cookie"] },
  { word: "빵", aliases: ["bread"] },
  { word: "치즈", aliases: ["cheese"] },
  { word: "달걀", aliases: ["계란", "egg"] },
  { word: "우유", aliases: ["milk"] },
  { word: "커피", aliases: ["coffee"] },
  { word: "주스", aliases: ["juice"] },
  { word: "컵라면", aliases: ["컵 라면", "cup ramen"] },
  { word: "감자튀김", aliases: ["프렌치프라이", "french fries"] },
  { word: "초콜릿", aliases: ["chocolate"] },
  { word: "사탕", aliases: ["candy"] },
  { word: "팝콘", aliases: ["popcorn"] },
  { word: "생선", aliases: ["fish"] },
  { word: "닭다리", aliases: ["chicken leg"] },
  { word: "자동차", aliases: ["차", "car"] },
  { word: "버스", aliases: ["bus"] },
  { word: "택시", aliases: ["taxi"] },
  { word: "자전거", aliases: ["bike", "bicycle"] },
  { word: "오토바이", aliases: ["motorcycle"] },
  { word: "기차", aliases: ["train"] },
  { word: "지하철", aliases: ["subway"] },
  { word: "비행기", aliases: ["항공기", "airplane", "plane"] },
  { word: "헬리콥터", aliases: ["헬기", "helicopter"] },
  { word: "배", aliases: ["보트", "boat", "ship"] },
  { word: "로켓", aliases: ["rocket"] },
  { word: "트럭", aliases: ["truck"] },
  { word: "구급차", aliases: ["ambulance"] },
  { word: "소방차", aliases: ["fire truck"] },
  { word: "경찰차", aliases: ["police car"] },
  { word: "스케이트보드", aliases: ["skateboard"] },
  { word: "킥보드", aliases: ["scooter"] },
  { word: "유모차", aliases: ["stroller"] },
  { word: "잠수함", aliases: ["submarine"] },
  { word: "열기구", aliases: ["hot air balloon"] },
  { word: "우산", aliases: ["umbrella"] },
  { word: "가방", aliases: ["bag"] },
  { word: "책", aliases: ["book"] },
  { word: "연필", aliases: ["pencil"] },
  { word: "지우개", aliases: ["eraser"] },
  { word: "가위", aliases: ["scissors"] },
  { word: "테이프", aliases: ["tape"] },
  { word: "시계", aliases: ["watch", "clock"] },
  { word: "안경", aliases: ["glasses"] },
  { word: "모자", aliases: ["hat", "cap"] },
  { word: "신발", aliases: ["shoe", "shoes"] },
  { word: "양말", aliases: ["sock", "socks"] },
  { word: "티셔츠", aliases: ["shirt", "t-shirt"] },
  { word: "바지", aliases: ["pants"] },
  { word: "의자", aliases: ["chair"] },
  { word: "책상", aliases: ["desk"] },
  { word: "침대", aliases: ["bed"] },
  { word: "소파", aliases: ["sofa", "couch"] },
  { word: "문", aliases: ["door"] },
  { word: "창문", aliases: ["window"] },
  { word: "열쇠", aliases: ["key"] },
  { word: "자물쇠", aliases: ["lock"] },
  { word: "컵", aliases: ["cup"] },
  { word: "접시", aliases: ["plate"] },
  { word: "숟가락", aliases: ["spoon"] },
  { word: "포크", aliases: ["fork"] },
  { word: "칫솔", aliases: ["toothbrush"] },
  { word: "치약", aliases: ["toothpaste"] },
  { word: "비누", aliases: ["soap"] },
  { word: "수건", aliases: ["towel"] },
  { word: "휴지", aliases: ["tissue", "toilet paper"] },
  { word: "전구", aliases: ["light bulb"] },
  { word: "손전등", aliases: ["flashlight"] },
  { word: "카메라", aliases: ["camera"] },
  { word: "휴대폰", aliases: ["핸드폰", "phone"] },
  { word: "컴퓨터", aliases: ["computer"] },
  { word: "키보드", aliases: ["keyboard"] },
  { word: "마우스", aliases: ["mouse"] },
  { word: "텔레비전", aliases: ["티비", "TV", "television"] },
  { word: "리모컨", aliases: ["remote"] },
  { word: "냉장고", aliases: ["refrigerator", "fridge"] },
  { word: "세탁기", aliases: ["washing machine"] },
  { word: "전자레인지", aliases: ["microwave"] },
  { word: "선풍기", aliases: ["fan"] },
  { word: "에어컨", aliases: ["air conditioner"] },
  { word: "태양", aliases: ["해", "sun"] },
  { word: "달", aliases: ["moon"] },
  { word: "별", aliases: ["star"] },
  { word: "구름", aliases: ["cloud"] },
  { word: "비", aliases: ["rain"] },
  { word: "눈", aliases: ["snow"] },
  { word: "번개", aliases: ["lightning"] },
  { word: "무지개", aliases: ["rainbow"] },
  { word: "산", aliases: ["mountain"] },
  { word: "바다", aliases: ["sea", "ocean"] },
  { word: "강", aliases: ["river"] },
  { word: "호수", aliases: ["lake"] },
  { word: "나무", aliases: ["tree"] },
  { word: "꽃", aliases: ["flower"] },
  { word: "잎", aliases: ["나뭇잎", "leaf"] },
  { word: "선인장", aliases: ["cactus"] },
  { word: "바위", aliases: ["rock"] },
  { word: "불", aliases: ["fire"] },
  { word: "파도", aliases: ["wave"] },
  { word: "섬", aliases: ["island"] },
  { word: "화산", aliases: ["volcano"] },
  { word: "눈사람", aliases: ["snowman"] },
  { word: "우주", aliases: ["space"] },
  { word: "행성", aliases: ["planet"] },
  { word: "해변", aliases: ["beach"] },
  { word: "집", aliases: ["house", "home"] },
  { word: "학교", aliases: ["school"] },
  { word: "병원", aliases: ["hospital"] },
  { word: "도서관", aliases: ["library"] },
  { word: "영화관", aliases: ["cinema", "movie theater"] },
  { word: "공원", aliases: ["park"] },
  { word: "놀이터", aliases: ["playground"] },
  { word: "식당", aliases: ["restaurant"] },
  { word: "카페", aliases: ["cafe"] },
  { word: "편의점", aliases: ["convenience store"] },
  { word: "은행", aliases: ["bank"] },
  { word: "우체국", aliases: ["post office"] },
  { word: "공항", aliases: ["airport"] },
  { word: "역", aliases: ["station"] },
  { word: "다리", aliases: ["bridge"] },
  { word: "성", aliases: ["castle"] },
  { word: "텐트", aliases: ["tent"] },
  { word: "교회", aliases: ["church"] },
  { word: "경기장", aliases: ["stadium"] },
  { word: "수영장", aliases: ["pool", "swimming pool"] },
  { word: "축구공", aliases: ["soccer ball", "football"] },
  { word: "농구공", aliases: ["basketball"] },
  { word: "야구방망이", aliases: ["야구 배트", "baseball bat"] },
  { word: "테니스라켓", aliases: ["테니스 라켓", "tennis racket"] },
  { word: "골프채", aliases: ["golf club"] },
  { word: "볼링핀", aliases: ["bowling pin"] },
  { word: "스키", aliases: ["ski"] },
  { word: "스케이트", aliases: ["skate"] },
  { word: "낚싯대", aliases: ["낚시대", "fishing rod"] },
  { word: "기타", aliases: ["guitar"] },
  { word: "피아노", aliases: ["piano"] },
  { word: "드럼", aliases: ["drum"] },
  { word: "마이크", aliases: ["microphone", "mic"] },
  { word: "팔레트", aliases: ["palette"] },
  { word: "주사위", aliases: ["dice"] },
  { word: "손", aliases: ["hand"] },
  { word: "발", aliases: ["foot"] },
  { word: "귀", aliases: ["ear"] },
  { word: "코", aliases: ["nose"] },
  { word: "입", aliases: ["mouth"] },
  { word: "하트", aliases: ["heart"] },
  { word: "왕관", aliases: ["crown"] },
  { word: "선물상자", aliases: ["선물", "gift box", "present"] },
  { word: "풍선", aliases: ["balloon"] },
  { word: "깃발", aliases: ["flag"] },
] satisfies DrawDuelWordEntry[];

export function drawDuelWordCategoryFor(word: string): DrawDuelWordCategory | undefined {
  const index = drawDuelWordBank.findIndex((entry) => entry.word === word);

  if (index < 0) {
    return undefined;
  }

  const oneBasedIndex = index + 1;

  return wordCategoryRanges.find((range) => oneBasedIndex <= range.end)?.category;
}
