import type { RealOrAiPrivateRoundItem } from "@ai-arcade/shared";

// Generated by `pnpm --filter realtime-server real-or-ai:assets`.
// Do not edit by hand. Source images live in local-only /real_images and /ai_images.
export const realOrAiRoundItems = [
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-001-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-001-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-001-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-001-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-001-a",
    id: "item-001",
    title: "사진 비교 001"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-002-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-002-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-002-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-002-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-002-a",
    id: "item-002",
    title: "사진 비교 002"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-003-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-003-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-003-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-003-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-003-b",
    id: "item-003",
    title: "사진 비교 003"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-004-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-004-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-004-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-004-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-004-a",
    id: "item-004",
    title: "사진 비교 004"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-005-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-005-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-005-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-005-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-005-b",
    id: "item-005",
    title: "사진 비교 005"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-006-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-006-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-006-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-006-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-006-a",
    id: "item-006",
    title: "사진 비교 006"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-007-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-007-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-007-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-007-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-007-b",
    id: "item-007",
    title: "사진 비교 007"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-008-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-008-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-008-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-008-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-008-b",
    id: "item-008",
    title: "사진 비교 008"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-009-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-009-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-009-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-009-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-009-a",
    id: "item-009",
    title: "사진 비교 009"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-010-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-010-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-010-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-010-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-010-b",
    id: "item-010",
    title: "사진 비교 010"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-011-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-011-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-011-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-011-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-011-b",
    id: "item-011",
    title: "사진 비교 011"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-012-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-012-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-012-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-012-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-012-a",
    id: "item-012",
    title: "사진 비교 012"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-013-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-013-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-013-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-013-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-013-b",
    id: "item-013",
    title: "사진 비교 013"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-014-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-014-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-014-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-014-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-014-b",
    id: "item-014",
    title: "사진 비교 014"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-015-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-015-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-015-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-015-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-015-a",
    id: "item-015",
    title: "사진 비교 015"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-016-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-016-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-016-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-016-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-016-b",
    id: "item-016",
    title: "사진 비교 016"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-017-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-017-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-017-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-017-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-017-a",
    id: "item-017",
    title: "사진 비교 017"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-018-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-018-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-018-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-018-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-018-a",
    id: "item-018",
    title: "사진 비교 018"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-019-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-019-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-019-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-019-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-019-b",
    id: "item-019",
    title: "사진 비교 019"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-020-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-020-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-020-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-020-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-020-a",
    id: "item-020",
    title: "사진 비교 020"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-021-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-021-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-021-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-021-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-021-b",
    id: "item-021",
    title: "사진 비교 021"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-022-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-022-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-022-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-022-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-022-b",
    id: "item-022",
    title: "사진 비교 022"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-023-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-023-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-023-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-023-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-023-a",
    id: "item-023",
    title: "사진 비교 023"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-024-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-024-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-024-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-024-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-024-a",
    id: "item-024",
    title: "사진 비교 024"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-025-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-025-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-025-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-025-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-025-a",
    id: "item-025",
    title: "사진 비교 025"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-026-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-026-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-026-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-026-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-026-b",
    id: "item-026",
    title: "사진 비교 026"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-027-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-027-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-027-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-027-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-027-a",
    id: "item-027",
    title: "사진 비교 027"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-028-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-028-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-028-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-028-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-028-b",
    id: "item-028",
    title: "사진 비교 028"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-029-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-029-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-029-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-029-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-029-b",
    id: "item-029",
    title: "사진 비교 029"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-030-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-030-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-030-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-030-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-030-a",
    id: "item-030",
    title: "사진 비교 030"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-031-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-031-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-031-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-031-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-031-b",
    id: "item-031",
    title: "사진 비교 031"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-032-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-032-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-032-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-032-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-032-b",
    id: "item-032",
    title: "사진 비교 032"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-033-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-033-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-033-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-033-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-033-b",
    id: "item-033",
    title: "사진 비교 033"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-034-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-034-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-034-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-034-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-034-b",
    id: "item-034",
    title: "사진 비교 034"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-035-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-035-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-035-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-035-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-035-b",
    id: "item-035",
    title: "사진 비교 035"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-036-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-036-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-036-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-036-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-036-b",
    id: "item-036",
    title: "사진 비교 036"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-037-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-037-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-037-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-037-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-037-a",
    id: "item-037",
    title: "사진 비교 037"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-038-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-038-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-038-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-038-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-038-b",
    id: "item-038",
    title: "사진 비교 038"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-039-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-039-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-039-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-039-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-039-b",
    id: "item-039",
    title: "사진 비교 039"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-040-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-040-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-040-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-040-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-040-a",
    id: "item-040",
    title: "사진 비교 040"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-041-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-041-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-041-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-041-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-041-b",
    id: "item-041",
    title: "사진 비교 041"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-042-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-042-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-042-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-042-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-042-b",
    id: "item-042",
    title: "사진 비교 042"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-043-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-043-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-043-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-043-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-043-a",
    id: "item-043",
    title: "사진 비교 043"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-044-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-044-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-044-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-044-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-044-a",
    id: "item-044",
    title: "사진 비교 044"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-045-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-045-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-045-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-045-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-045-b",
    id: "item-045",
    title: "사진 비교 045"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-046-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-046-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-046-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-046-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-046-a",
    id: "item-046",
    title: "사진 비교 046"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-047-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-047-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-047-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-047-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-047-b",
    id: "item-047",
    title: "사진 비교 047"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-048-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-048-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-048-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-048-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-048-a",
    id: "item-048",
    title: "사진 비교 048"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-049-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-049-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-049-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-049-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-049-a",
    id: "item-049",
    title: "사진 비교 049"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-050-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-050-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-050-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-050-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-050-a",
    id: "item-050",
    title: "사진 비교 050"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-051-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-051-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-051-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-051-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-051-a",
    id: "item-051",
    title: "사진 비교 051"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-052-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-052-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-052-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-052-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-052-a",
    id: "item-052",
    title: "사진 비교 052"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-053-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-053-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-053-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-053-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-053-a",
    id: "item-053",
    title: "사진 비교 053"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-054-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-054-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-054-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-054-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-054-a",
    id: "item-054",
    title: "사진 비교 054"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-055-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-055-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-055-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-055-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-055-b",
    id: "item-055",
    title: "사진 비교 055"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-056-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-056-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-056-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-056-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-056-b",
    id: "item-056",
    title: "사진 비교 056"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-057-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-057-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-057-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-057-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-057-b",
    id: "item-057",
    title: "사진 비교 057"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-058-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-058-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-058-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-058-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-058-b",
    id: "item-058",
    title: "사진 비교 058"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-059-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-059-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-059-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-059-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-059-b",
    id: "item-059",
    title: "사진 비교 059"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-060-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-060-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-060-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-060-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-060-b",
    id: "item-060",
    title: "사진 비교 060"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-061-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-061-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-061-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-061-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-061-a",
    id: "item-061",
    title: "사진 비교 061"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-062-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-062-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-062-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-062-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-062-a",
    id: "item-062",
    title: "사진 비교 062"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-063-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-063-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-063-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-063-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-063-a",
    id: "item-063",
    title: "사진 비교 063"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-064-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-064-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-064-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-064-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-064-a",
    id: "item-064",
    title: "사진 비교 064"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-065-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-065-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-065-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-065-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-065-b",
    id: "item-065",
    title: "사진 비교 065"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-066-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-066-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-066-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-066-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-066-a",
    id: "item-066",
    title: "사진 비교 066"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-067-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-067-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-067-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-067-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-067-b",
    id: "item-067",
    title: "사진 비교 067"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-068-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-068-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-068-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-068-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-068-a",
    id: "item-068",
    title: "사진 비교 068"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-069-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-069-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-069-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-069-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-069-b",
    id: "item-069",
    title: "사진 비교 069"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-070-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-070-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-070-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-070-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-070-a",
    id: "item-070",
    title: "사진 비교 070"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-071-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-071-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-071-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-071-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-071-a",
    id: "item-071",
    title: "사진 비교 071"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-072-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-072-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-072-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-072-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-072-b",
    id: "item-072",
    title: "사진 비교 072"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-073-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-073-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-073-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-073-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-073-b",
    id: "item-073",
    title: "사진 비교 073"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-074-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-074-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-074-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-074-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-074-a",
    id: "item-074",
    title: "사진 비교 074"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-075-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-075-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-075-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-075-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-075-a",
    id: "item-075",
    title: "사진 비교 075"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-076-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-076-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-076-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-076-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-076-b",
    id: "item-076",
    title: "사진 비교 076"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-077-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-077-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-077-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-077-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-077-b",
    id: "item-077",
    title: "사진 비교 077"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-078-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-078-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-078-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-078-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-078-a",
    id: "item-078",
    title: "사진 비교 078"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-079-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-079-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-079-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-079-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-079-a",
    id: "item-079",
    title: "사진 비교 079"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-080-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-080-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-080-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-080-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-080-a",
    id: "item-080",
    title: "사진 비교 080"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-081-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-081-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-081-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-081-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-081-a",
    id: "item-081",
    title: "사진 비교 081"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-082-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-082-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-082-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-082-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-082-b",
    id: "item-082",
    title: "사진 비교 082"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-083-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-083-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-083-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-083-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-083-b",
    id: "item-083",
    title: "사진 비교 083"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-084-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-084-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-084-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-084-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-084-a",
    id: "item-084",
    title: "사진 비교 084"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-085-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-085-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-085-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-085-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-085-a",
    id: "item-085",
    title: "사진 비교 085"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-086-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-086-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-086-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-086-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-086-b",
    id: "item-086",
    title: "사진 비교 086"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-087-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-087-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-087-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-087-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-087-b",
    id: "item-087",
    title: "사진 비교 087"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-088-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-088-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-088-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-088-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-088-b",
    id: "item-088",
    title: "사진 비교 088"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-089-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-089-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-089-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-089-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-089-a",
    id: "item-089",
    title: "사진 비교 089"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-090-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-090-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-090-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-090-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-090-a",
    id: "item-090",
    title: "사진 비교 090"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-091-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-091-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-091-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-091-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-091-a",
    id: "item-091",
    title: "사진 비교 091"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-092-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-092-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-092-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-092-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-092-a",
    id: "item-092",
    title: "사진 비교 092"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-093-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-093-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-093-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-093-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-093-b",
    id: "item-093",
    title: "사진 비교 093"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-094-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-094-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-094-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-094-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-094-a",
    id: "item-094",
    title: "사진 비교 094"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-095-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-095-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-095-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-095-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-095-b",
    id: "item-095",
    title: "사진 비교 095"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-096-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-096-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-096-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-096-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-096-b",
    id: "item-096",
    title: "사진 비교 096"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-097-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-097-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-097-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-097-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-097-a",
    id: "item-097",
    title: "사진 비교 097"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-098-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-098-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-098-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-098-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-098-b",
    id: "item-098",
    title: "사진 비교 098"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-099-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-099-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-099-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-099-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-099-b",
    id: "item-099",
    title: "사진 비교 099"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-100-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-100-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-100-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-100-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-100-a",
    id: "item-100",
    title: "사진 비교 100"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-101-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-101-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-101-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-101-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-101-b",
    id: "item-101",
    title: "사진 비교 101"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-102-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-102-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-102-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-102-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-102-b",
    id: "item-102",
    title: "사진 비교 102"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-103-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-103-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-103-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-103-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-103-a",
    id: "item-103",
    title: "사진 비교 103"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-104-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-104-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-104-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-104-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-104-a",
    id: "item-104",
    title: "사진 비교 104"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-105-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-105-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-105-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-105-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-105-b",
    id: "item-105",
    title: "사진 비교 105"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-106-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-106-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-106-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-106-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-106-b",
    id: "item-106",
    title: "사진 비교 106"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-107-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-107-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-107-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-107-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-107-b",
    id: "item-107",
    title: "사진 비교 107"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-108-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-108-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-108-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-108-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-108-b",
    id: "item-108",
    title: "사진 비교 108"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-109-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-109-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-109-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-109-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-109-b",
    id: "item-109",
    title: "사진 비교 109"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-110-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-110-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-110-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-110-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-110-a",
    id: "item-110",
    title: "사진 비교 110"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-111-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-111-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-111-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-111-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-111-a",
    id: "item-111",
    title: "사진 비교 111"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-112-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-112-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-112-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-112-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-112-b",
    id: "item-112",
    title: "사진 비교 112"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-113-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-113-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-113-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-113-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-113-b",
    id: "item-113",
    title: "사진 비교 113"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-114-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-114-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-114-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-114-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-114-a",
    id: "item-114",
    title: "사진 비교 114"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-115-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-115-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-115-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-115-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-115-b",
    id: "item-115",
    title: "사진 비교 115"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-116-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-116-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-116-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-116-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-116-a",
    id: "item-116",
    title: "사진 비교 116"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-117-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-117-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-117-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-117-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-117-b",
    id: "item-117",
    title: "사진 비교 117"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-118-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-118-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-118-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-118-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-118-b",
    id: "item-118",
    title: "사진 비교 118"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-119-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-119-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-119-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-119-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-119-b",
    id: "item-119",
    title: "사진 비교 119"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-120-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-120-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-120-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-120-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-120-a",
    id: "item-120",
    title: "사진 비교 120"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-121-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-121-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-121-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-121-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-121-a",
    id: "item-121",
    title: "사진 비교 121"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-122-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-122-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-122-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-122-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-122-a",
    id: "item-122",
    title: "사진 비교 122"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-123-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-123-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-123-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-123-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-123-a",
    id: "item-123",
    title: "사진 비교 123"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-124-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-124-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-124-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-124-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-124-b",
    id: "item-124",
    title: "사진 비교 124"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-125-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-125-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-125-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-125-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-125-b",
    id: "item-125",
    title: "사진 비교 125"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-126-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-126-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-126-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-126-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-126-b",
    id: "item-126",
    title: "사진 비교 126"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-127-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-127-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-127-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-127-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-127-b",
    id: "item-127",
    title: "사진 비교 127"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 900,
        id: "item-128-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-128-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 720,
        id: "item-128-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-128-b.webp",
        width: 1280
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-128-b",
    id: "item-128",
    title: "사진 비교 128"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-129-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-129-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-129-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-129-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-129-a",
    id: "item-129",
    title: "사진 비교 129"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 720,
        id: "item-130-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-130-a.webp",
        width: 1280
      },
      {
        alt: "후보 B 사진",
        height: 900,
        id: "item-130-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-130-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-130-a",
    id: "item-130",
    title: "사진 비교 130"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1068,
        id: "item-131-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-131-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-131-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-131-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-131-a",
    id: "item-131",
    title: "사진 비교 131"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1536,
        id: "item-132-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-132-a.webp",
        width: 1024
      },
      {
        alt: "후보 B 사진",
        height: 1600,
        id: "item-132-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-132-b.webp",
        width: 1067
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-132-b",
    id: "item-132",
    title: "사진 비교 132"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1067,
        id: "item-133-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-133-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-133-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-133-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-133-a",
    id: "item-133",
    title: "사진 비교 133"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1067,
        id: "item-134-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-134-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-134-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-134-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-134-a",
    id: "item-134",
    title: "사진 비교 134"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1600,
        id: "item-135-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-135-a.webp",
        width: 1068
      },
      {
        alt: "후보 B 사진",
        height: 1536,
        id: "item-135-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-135-b.webp",
        width: 1024
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-135-a",
    id: "item-135",
    title: "사진 비교 135"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1600,
        id: "item-136-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-136-a.webp",
        width: 1068
      },
      {
        alt: "후보 B 사진",
        height: 1536,
        id: "item-136-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-136-b.webp",
        width: 1024
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-136-a",
    id: "item-136",
    title: "사진 비교 136"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1536,
        id: "item-137-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-137-a.webp",
        width: 1024
      },
      {
        alt: "후보 B 사진",
        height: 1067,
        id: "item-137-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-137-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-137-b",
    id: "item-137",
    title: "사진 비교 137"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1600,
        id: "item-138-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-138-a.webp",
        width: 1066
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-138-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-138-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-138-a",
    id: "item-138",
    title: "사진 비교 138"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1536,
        id: "item-139-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-139-a.webp",
        width: 1024
      },
      {
        alt: "후보 B 사진",
        height: 1600,
        id: "item-139-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-139-b.webp",
        width: 1067
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-139-b",
    id: "item-139",
    title: "사진 비교 139"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1600,
        id: "item-140-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-140-a.webp",
        width: 949
      },
      {
        alt: "후보 B 사진",
        height: 1536,
        id: "item-140-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-140-b.webp",
        width: 1024
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-140-a",
    id: "item-140",
    title: "사진 비교 140"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1024,
        id: "item-141-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-141-a.webp",
        width: 1536
      },
      {
        alt: "후보 B 사진",
        height: 1066,
        id: "item-141-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-141-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-141-b",
    id: "item-141",
    title: "사진 비교 141"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1600,
        id: "item-142-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-142-a.webp",
        width: 1067
      },
      {
        alt: "후보 B 사진",
        height: 1536,
        id: "item-142-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-142-b.webp",
        width: 1024
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-142-a",
    id: "item-142",
    title: "사진 비교 142"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1600,
        id: "item-143-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-143-a.webp",
        width: 1067
      },
      {
        alt: "후보 B 사진",
        height: 1536,
        id: "item-143-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-143-b.webp",
        width: 1024
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-143-a",
    id: "item-143",
    title: "사진 비교 143"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1536,
        id: "item-144-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-144-a.webp",
        width: 1024
      },
      {
        alt: "후보 B 사진",
        height: 1600,
        id: "item-144-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-144-b.webp",
        width: 1068
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-144-b",
    id: "item-144",
    title: "사진 비교 144"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1068,
        id: "item-145-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-145-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-145-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-145-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-145-a",
    id: "item-145",
    title: "사진 비교 145"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1536,
        id: "item-146-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-146-a.webp",
        width: 1024
      },
      {
        alt: "후보 B 사진",
        height: 1600,
        id: "item-146-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-146-b.webp",
        width: 1067
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-146-b",
    id: "item-146",
    title: "사진 비교 146"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1068,
        id: "item-147-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-147-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-147-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-147-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-147-a",
    id: "item-147",
    title: "사진 비교 147"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1024,
        id: "item-148-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-148-a.webp",
        width: 1536
      },
      {
        alt: "후보 B 사진",
        height: 1068,
        id: "item-148-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-148-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-148-b",
    id: "item-148",
    title: "사진 비교 148"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1536,
        id: "item-149-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-149-a.webp",
        width: 1024
      },
      {
        alt: "후보 B 사진",
        height: 1068,
        id: "item-149-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-149-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-149-b",
    id: "item-149",
    title: "사진 비교 149"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1024,
        id: "item-150-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-150-a.webp",
        width: 1536
      },
      {
        alt: "후보 B 사진",
        height: 1067,
        id: "item-150-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-150-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-150-b",
    id: "item-150",
    title: "사진 비교 150"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1024,
        id: "item-151-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-151-a.webp",
        width: 1536
      },
      {
        alt: "후보 B 사진",
        height: 1067,
        id: "item-151-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-151-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-151-b",
    id: "item-151",
    title: "사진 비교 151"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1067,
        id: "item-152-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-152-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-152-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-152-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-152-a",
    id: "item-152",
    title: "사진 비교 152"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1067,
        id: "item-153-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-153-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-153-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-153-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-153-a",
    id: "item-153",
    title: "사진 비교 153"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1600,
        id: "item-154-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-154-a.webp",
        width: 1067
      },
      {
        alt: "후보 B 사진",
        height: 1536,
        id: "item-154-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-154-b.webp",
        width: 1024
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-154-a",
    id: "item-154",
    title: "사진 비교 154"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1536,
        id: "item-155-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-155-a.webp",
        width: 1024
      },
      {
        alt: "후보 B 사진",
        height: 1600,
        id: "item-155-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-155-b.webp",
        width: 1200
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-155-b",
    id: "item-155",
    title: "사진 비교 155"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1067,
        id: "item-156-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-156-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-156-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-156-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-156-a",
    id: "item-156",
    title: "사진 비교 156"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1066,
        id: "item-157-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-157-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-157-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-157-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-157-a",
    id: "item-157",
    title: "사진 비교 157"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1024,
        id: "item-158-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-158-a.webp",
        width: 1536
      },
      {
        alt: "후보 B 사진",
        height: 1069,
        id: "item-158-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-158-b.webp",
        width: 1600
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-158-b",
    id: "item-158",
    title: "사진 비교 158"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1536,
        id: "item-159-a",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-159-a.webp",
        width: 1024
      },
      {
        alt: "후보 B 사진",
        height: 1600,
        id: "item-159-b",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-159-b.webp",
        width: 1200
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-159-b",
    id: "item-159",
    title: "사진 비교 159"
  },
  {
    candidates: [
      {
        alt: "후보 A 사진",
        height: 1068,
        id: "item-160-a",
        sourceType: "real",
        src: "/games/real-or-ai/images/item-160-a.webp",
        width: 1600
      },
      {
        alt: "후보 B 사진",
        height: 1024,
        id: "item-160-b",
        sourceType: "ai",
        src: "/games/real-or-ai/images/item-160-b.webp",
        width: 1536
      }
    ],
    category: "photo-pair",
    correctCandidateId: "item-160-a",
    id: "item-160",
    title: "사진 비교 160"
  }
] satisfies RealOrAiPrivateRoundItem[];
